name: knapptimecreative
favicon: null
layout_spectrum: 0.48758
typography_spectrum: 0.28082
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e22f39'
    - '#fffeff'
    - '#ff0000'
    - '#ec6b69'
    - '#ffdbdb'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
